apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: host.minikube.internal/secure-file-upload/backend:v2
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: secure-file-secret

          ports:
            - containerPort: 5001